services:
  crypto-cli:
    build: .
    image: crypto-cli
    container_name: crypto-cli
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - TERM=xterm-256color
      - COLORTERM=truecolor
      - FORCE_COLOR=1
    env_file:
      - .env
    stdin_open: true
    tty: true
